/*
	Manipular uma promessa rejeitada usando o catch

	catch é o método usado quando a promessa é rejeitada. Ele é executado
	imediatamente após o método reject da promessa ser chamado. Aqui está a
	sintaxe:

	myPromise.catch(error => {

	});

	O parâmetro error é o argumento passado para o método reject.
*/

// use de catch para manipulao de erros
myPromise.catch(error => {});